# Generated by Django 5.1.7 on 2025-03-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Blok Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloklar',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Harcama Başlığı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('date', models.DateField(verbose_name='Harcama Tarihi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Harcama',
                'verbose_name_plural': 'Harcamalar',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Daire Numarası')),
                ('is_occupied', models.BooleanField(default=True, verbose_name='Dolu mu?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Daire Sahibi')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block', verbose_name='Blok')),
            ],
            options={
                'verbose_name': 'Daire',
                'verbose_name_plural': 'Daireler',
            },
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('due_date', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment', verbose_name='Daire')),
            ],
            options={
                'verbose_name': 'Aidat',
                'verbose_name_plural': 'Aidatlar',
            },
        ),
    ]
